In [1]:
import pandas as pd
import numpy as np

In [12]:
#series
n1 = np.array([1,2,3,4,5])
s1 = pd.Series([1,2,3,4,5])
#print(n1)
#print(s1)

#s = pd.Series([1, 3, 5, np.nan, 6, pd.NaT])
#s1 = pd.Series({2:'a', 1:'b', 3:'c'}) #, index=[100,10]
#s2 = pd.Series([10,12], index=[100,200])
s3 = pd.Series(5, index=[100,2,5,6,8])
print(s3)

100    5
2      5
5      5
6      5
8      5
dtype: int64

In [26]:
#DataFrame
df = pd.DataFrame({'Name':["Ajay",'Vijay','Sunil'], 'BZ':[4,5,6], 'CD':[7,8,9]})
df

    Name  BZ  CD
0   Ajay   4   7
1  Vijay   5   8
2  Sunil   6   9

In [28]:
df = pd.read_csv("/content/Sample - Superstore - full.csv", encoding='latin-1')#

In [15]:
df

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,CA-2016-138688,12-06-2016,16-06-2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,CA-2014-110422,21-01-2014,23-01-2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,CA-2017-119914,04-05-2017,09-05-2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [16]:
#df.to_excel('abc.xlsx')

In [ ]:
#head(),tail(),info(),describe(),shape,columns,dtypes

In [18]:
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [20]:
df.tail(2)

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9992,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.60,4,0.0,13.320
9993,CA-2017-119914,04-05-2017,09-05-2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.16,2,0.0,72.948

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       9994 non-null   object
 1   Order Date     9994 non-null   object
 2   Ship Date      9994 non-null   object
 3   Ship Mode      9994 non-null   object
 4   Customer ID    9994 non-null   object
 5   Customer Name  9994 non-null   object
 6   Segment        9994 non-null   object
 7   Country        9994 non-null   object
 8   City           9994 non-null   object
 9   State          9994 non-null   object
 10  Postal Code    9994 non-null   int64
 11  Region         9994 non-null   object
 12  Product ID     9994 non-null   object
 13  Category       9994 non-null   object
 14  Sub-Category   9994 non-null   object
 15  Product Name   9994 non-null   object
 16  Sales          9994 non-null   float64
 17  Quantity       9994 non-null   int64
 18  Discount       9994 non-null   float64
 19  Profit         9994 non-null   float64
dtypes: float64(3), int64(2), object(15)
memory usage: 1.5+ MB

In [ ]:
df.describe()

        Postal Code         Sales     Quantity     Discount       Profit
count   9994.000000   9994.000000  9994.000000  9994.000000  9994.000000
mean   55190.379428    229.858001     3.789574     0.156203    28.656896
std    32063.693350    623.245101     2.225110     0.206452   234.260108
min     1040.000000      0.444000     1.000000     0.000000 -6599.978000
25%    23223.000000     17.280000     2.000000     0.000000     1.728750
50%    56430.500000     54.490000     3.000000     0.200000     8.666500
75%    90008.000000    209.940000     5.000000     0.200000    29.364000
max    99301.000000  22638.480000    14.000000     0.800000  8399.976000

In [ ]:
print(df.shape)
print(df.dtypes)

(9994, 20)
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [ ]:
df.columns

Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code',
       'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name',
       'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [ ]:
#orderid = df['Order ID']
orderid = df[['Order ID','Sales','Discount']]
orderid

            Order ID     Sales  Discount
0     CA-2016-152156  261.9600      0.00
1     CA-2016-152156  731.9400      0.00
2     CA-2016-138688   14.6200      0.00
3     US-2015-108966  957.5775      0.45
4     US-2015-108966   22.3680      0.20
...              ...       ...       ...
9989  CA-2014-110422   25.2480      0.20
9990  CA-2017-121258   91.9600      0.00
9991  CA-2017-121258  258.5760      0.20
9992  CA-2017-121258   29.6000      0.00
9993  CA-2017-119914  243.1600      0.00

[9994 rows x 3 columns]

In [40]:
df1 = df[['Order ID','Region','Sales']]
df1

df2 = df1[(df1['Region']=="South")&(df1['Sales']>=5000)]
print(df2)

            Order ID Region     Sales
509   CA-2015-145352  South   6354.95
683   US-2017-168116  South   7999.98
2697  CA-2014-145317  South  22638.48
8488  CA-2016-158841  South   8749.95

In [ ]:
df1 = df[df['Region']=='East']
df1.shape

(3203, 20)

In [53]:
df = pd.read_csv("/content/Sample - Superstore - full.csv", encoding='latin-1')#

#df.drop(columns=['Order ID','Ship Mode'])#, inplace=True)
df.drop(['Order ID','Ship Mode'], axis=1)

,Order Date,Ship Date,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,08-11-2016,11-11-2016,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,08-11-2016,11-11-2016,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,12-06-2016,16-06-2016,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,11-10-2015,18-10-2015,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,11-10-2015,18-10-2015,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,21-01-2014,23-01-2014,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,26-02-2017,03-03-2017,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,26-02-2017,03-03-2017,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,26-02-2017,03-03-2017,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,04-05-2017,09-05-2017,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [52]:
df.head(2)

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [56]:
#df.drop([0,1,2,3,4,5,6], axis=0,inplace=True)
#df.head(2)

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
7,CA-2014-115812,09-06-2014,14-06-2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.152,6,0.2,90.7152
8,CA-2014-115812,09-06-2014,14-06-2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.504,3,0.2,5.7825

In [ ]:
#Handling Missing Data
#fillna(),dropna()

In [ ]:
df1 = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
                   "toy": [np.nan, 'Batmobile', 'Bullwhip'],
                   "born": [pd.NaT, pd.Timestamp("1940-04-25"),
                            None]})
df1

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [ ]:
df2 = df1.dropna()
df2

     name        toy       born
1  Batman  Batmobile 1940-04-25

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame([[np.nan, 2, np.nan, 0],
                   [3, 4, np.nan, 1],
                   [np.nan, np.nan, np.nan, np.nan],
                   [np.nan, 3, np.nan, 4]],
                  columns=list("ABCD"))
df

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [ ]:
df.to_csv('data.csv')

In [ ]:
df1 = df.fillna(df.mean())
df1

     A    B   C         D
0  3.0  2.0 NaN  0.000000
1  3.0  4.0 NaN  1.000000
2  3.0  3.0 NaN  1.666667
3  3.0  3.0 NaN  4.000000

In [ ]:
df['A'].fillna(df['A'].mean(), inplace=True)
df['C'].fillna("-", inplace=True)
df

/tmp/ipython-input-3922773402.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['A'].fillna(df['A'].mean(), inplace=True)
/tmp/ipython-input-3922773402.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['C'].fillna("-", inplace=True)
/tmp/ipython-input-3922773402.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['C'].fillna("-", inplace=True)

     A    B  C    D
0  3.0  2.0  -  0.0
1  3.0  4.0  -  1.0
2  3.0  NaN  -  NaN
3  3.0  3.0  -  4.0

In [ ]:
data = {'A': [1, 2, None, 4],
        'B': [5, None, 7, 8]}
df = pd.DataFrame(data)
#df1 = df.fillna(df.mean())
#df1

df['A'].fillna(df['A'].mode()) #, inplace=True
df

     A    B
0  1.0  5.0
1  2.0  NaN
2  NaN  7.0
3  4.0  8.0

In [ ]:
df1=df
df1

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,12-06-2016,16-06-2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,21-01-2014,23-01-2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,04-05-2017,09-05-2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [61]:
df = pd.read_csv("/content/diamonds.csv", encoding='latin-1')#
df1 = df
df1.head()
#df1.loc[1000:1100,['clarity','color','cut']]
df1.iloc[1000:1100,2:5]

            cut color clarity
1000      Ideal     D     SI1
1001      Ideal     D     SI1
1002       Good     H     SI2
1003      Ideal     G     SI1
1004      Ideal     G     SI1
...         ...   ...     ...
1095    Premium     E     SI1
1096       Fair     H     SI2
1097       Fair     I     SI1
1098       Fair     H     SI2
1099  Very Good     D     VS2

[100 rows x 3 columns]

In [ ]:
#df1.loc[0:10,['Ship Mode','Order ID']]
#df1.iloc[0:10,2:5]

In [ ]:
#multi-indexing in Series
#import pandas as pd
index1 = [('California', 2010), ('California', 2020),
         ('New York', 2010), ('New York', 2020),
         ('Texas', 2010), ('Texas', 2020)]

#index1 = ['California','California','New York','New York','Texas', 'Texas']
populations = [37253956, 39538223,
               19378102, 20201249,
               25145561, 29145505]
pop = pd.Series(populations, index=index1)
pop

(California, 2010)    37253956
(California, 2020)    39538223
(New York, 2010)      19378102
(New York, 2020)      20201249
(Texas, 2010)         25145561
(Texas, 2020)         29145505
dtype: int64

In [ ]:
#abc = [['A','A','A','B','B','B'],[1,2,3,1,2,3]]
#abc = [('A',1),('A',2),('B',1),('B',2),('B',3),('B',4)]
abc = [['A','B'],[1,2,3]]

index1 = pd.MultiIndex.from_product(abc, names=('Class', 'Roll no.'))
df = pd.DataFrame({'Value': [10,20,30,40,50,60]},index=index1)
df

                Value
Class Roll no.
A     1            10
      2            20
      3            30
B     1            40
      2            50
      3            60

In [ ]:
#multi-indexing
import pandas as pd
#abc = [['A', 'B', 'D', 'C'],[1, 2, 3, 4]]
#index1 = pd.MultiIndex.from_arrays(abc, names=('Letter', 'Number'))
#df = pd.DataFrame({'Value': [10, 20, 30, 40]}, index=index1)
#print(df)



abc = [['A', 'B'],[1, 2, 3]]
index = pd.MultiIndex.from_product(abc, names=('Letter', 'Number'))
df1 = pd.DataFrame({'Value': [10, 20, 30, 40, 50, 60]}, index=index)
print(df1)

               Value
Letter Number
A      1          10
       2          20
       3          30
B      1          40
       2          50
       3          60

In [ ]:
tuples = [('A', 1), ('A', 2), ('B', 1), ('B', 2)]
multi_index = pd.MultiIndex.from_tuples(tuples, names=('Letter', 'Number'))
df1 = pd.DataFrame({'Value': [10, 20, 30, 40]}, index=multi_index)
print(df1)
df1

               Value
Letter Number
A      1          10
       2          20
B      1          30
       2          40

               Value
Letter Number
A      1          10
       2          20
B      1          30
       2          40

In [ ]:
import pandas as pd
arrays = [['A', 'B'], [1, 2, 3]]
index = pd.MultiIndex.from_product(arrays, names=['Letter', 'Number'])
df1 = pd.DataFrame({'Value': [10, 20, 30, 40,50,60]}, index=index)
print(df1)
df2 = df1.reset_index()
print(df2)

               Value
Letter Number
A      1          10
       2          20
       3          30
B      1          40
       2          50
       3          60
  Letter  Number  Value
0      A       1     10
1      A       2     20
2      A       3     30
3      B       1     40
4      B       2     50
5      B       3     60

In [ ]:
#Dropping Level
df_dropped = df1.droplevel('Letter')
df_dropped

        Value
Number
1          10
2          20
3          30
1          40
2          50
3          60

In [ ]:
df0 = pd.DataFrame({'Roll_no':[1,2,3,4,5],'Name':['Ajay','Vijay','Sunil','Akshay','Krunal'],'Marks':[30,21,25,63,14]})
df0.reset_index()
#df0.transpose()
#df0.T

   index  Roll_no    Name  Marks
0      0        1    Ajay     30
1      1        2   Vijay     21
2      2        3   Sunil     25
3      3        4  Akshay     63
4      4        5  Krunal     14

In [ ]:
#Transposing Data Frame
df_transposed = df_dropped.T #df.transpose()

In [ ]:
print(df_dropped)
print(df_transposed)

        Value
Letter
A          10
A          20
A          30
B          40
B          50
B          60
Letter   A   A   A   B   B   B
Value   10  20  30  40  50  60

In [ ]:
df1
df1 = df1.reset_index()

In [ ]:
#df_1 = df1[['Letter','Value']]
print(df1)

df_1 = df1.drop(columns=['Letter'])
#print(df_1)
print(df_1)

  Letter  Number  Value
0      A       1     10
1      A       2     20
2      A       3     30
3      B       1     40
4      B       2     50
5      B       3     60
   Number  Value
0       1     10
1       2     20
2       3     30
3       1     40
4       2     50
5       3     60

In [ ]:
#Select and
df = df['name']
df = df[['name1','name2']]
#drop columns
df = df.drop(columns=['name1','name2'])
df = df.drop(['name1','name2'], axis=1) #inplace=True

#filter
df[df['name1']>1000]
df[(df['name1']>1000)&(df['name2']=='Sale')]

In [ ]:
df = pd.read_csv("/content/diamonds.csv")
df.head()

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75

In [ ]:
df1 = df.drop(columns=['Unnamed: 0'])
df1

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [ ]:
test =df1[(df['cut']=='Good')&(df['color']=='E')&(df['clarity']=='VS1')&(df['table']>62)]
test

       carat   cut color clarity  depth  table  price     x     y     z
2       0.23  Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
13023   0.31  Good     E     VS1   59.0   63.0    600  4.44  4.47  2.63
17108   1.00  Good     E     VS1   60.6   63.0   6822  6.28  6.42  3.85
17831   1.00  Good     E     VS1   60.0   65.0   7190  6.48  6.43  3.87
18540   1.00  Good     E     VS1   60.1   63.0   7556  6.42  6.45  3.87
31178   0.32  Good     E     VS1   60.3   64.0    756  4.42  4.44  2.67
31179   0.32  Good     E     VS1   59.5   64.0    756  4.42  4.45  2.64
34938   0.27  Good     E     VS1   57.5   63.0    377  4.24  4.28  2.45
35142   0.37  Good     E     VS1   62.8   65.0    889  4.51  4.54  2.84
36350   0.35  Good     E     VS1   61.3   65.0    938  4.51  4.53  2.77
41698   0.45  Good     E     VS1   61.7   63.0   1241  4.88  4.91  3.02
46359   0.51  Good     E     VS1   57.9   63.0   1760  5.24  5.39  3.08
47240   0.51  Good     E     VS1   61.3   63.0   1841  5.11  5.16  3.15
48121   0.56  Good     E     VS1   61.7   65.0   1938  5.21  5.23  3.22
49113   0.60  Good     E     VS1   58.1   63.0   2065  5.53  5.63  3.24
49936   0.58  Good     E     VS1   58.6   64.0   2185  5.40  5.46  3.18
51872   0.67  Good     E     VS1   60.4   65.0   2427  5.67  5.65  3.42

In [ ]:
print(df1.head())
test1 = df1.drop([0,2,4,6,8,7,8,10],axis=0)
print(test1.head())
#df1

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
    carat        cut color clarity  depth  table  price     x     y     z
1    0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3    0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
5    0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
9    0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39
11   0.23      Ideal     J     VS1   62.8   56.0    340  3.93  3.90  2.46

In [ ]:
#df1.loc[0:5,['depth','table','price','x','carat']]
#df1.loc[0:5,['x','y','z']]
df1.iloc[:,0]

0        0.23
1        0.21
2        0.23
3        0.29
4        0.31
         ...
53935    0.72
53936    0.72
53937    0.70
53938    0.86
53939    0.75
Name: carat, Length: 53940, dtype: float64

In [ ]:
#drop rows
df.drop([0,2],axis=0)

#loc and iloc
df.loc[:,['name1','name2']]
df.iloc[:,:]

In [ ]:
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['NY', 'LA', 'Chicago']
}
df = pd.DataFrame(data)
df

      Name  Age     City
0    Alice   25       NY
1      Bob   30       LA
2  Charlie   35  Chicago

In [ ]:
df1 = df.loc[0:,['Age','City']]
df1

   Age     City
0   25       NY
1   30       LA
2   35  Chicago

In [ ]:
df1 = df.iloc[0:2,0:3]
df1

    Name  Age City
0  Alice   25   NY
1    Bob   30   LA

In [ ]:
#Rename, sort, set index
df1_new = df.rename(columns={'Age':'Age1','City':'City1'})
print(df1_new)

#df1_new1 = df.sort_values(by='Age',ascending=False) #
df1_new1 = df.sort_values(by=['Age','City'],ascending=[False,True]) #
print(df1_new1)

df_new2 = df.set_index('Age')
print(df_new2)

      Name  Age1    City1
0    Alice    25       NY
1      Bob    30       LA
2  Charlie    35  Chicago
      Name  Age     City
2  Charlie   35  Chicago
1      Bob   30       LA
0    Alice   25       NY
        Name     City
Age
25     Alice       NY
30       Bob       LA
35   Charlie  Chicago

In [ ]:
#Merge and Join
import pandas as pd

df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']
})

df2 = pd.DataFrame({
    'ID': [2, 3, 4],
    'Score': [85, 90, 88]
})

merged = pd.merge(df1, df2, on='ID', how='left')#,how='left','right','inner','outer'
merged

   ID     Name  Score
0   1    Alice    NaN
1   2      Bob   85.0
2   3  Charlie   90.0

In [ ]:
df1 = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie']}, index=[1, 2, 3])
df2 = pd.DataFrame({'Score': [85, 90, 88]}, index=[2, 3, 4])
print(df1)
print(df2)
joined = df1.join(df2, how='outer')
print(joined)

      Name
1    Alice
2      Bob
3  Charlie
   Score
2     85
3     90
4     88
      Name  Score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   88.0

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#group by
data = {
    'Category': ['A', 'A', 'B', 'B', 'C'],
    'Region': ['East', 'West', 'West', 'East', 'East'],
    'Sales': [100, 150, 200, 250, 300],
    'Quantity': [1, 2, 3, 4, 5]
}
df = pd.DataFrame(data)
#print(df)
#df1 = df.groupby('Region')['Sales'].sum()
#df1
#df1.reset_index()

#df1 = df.groupby('Category')['Sales'].agg(['sum', 'min', 'max','count'])
#print(df1)

df1 = df.groupby(['Region','Category'])[['Sales','Quantity']].sum()
#print(df1)

df1 = df.groupby(['Region','Category']).agg({'Sales':'sum','Quantity':'mean'})
print(df1)



#df1 = df.groupby(['Category','Region'])['Sales'].mean() #min(),max(),count(),sum(),mode(),medain(),mean()
#print(df1.reset_index())

                 Sales  Quantity
Region Category
East   A           100       1.0
       B           250       4.0
       C           300       5.0
West   A           150       2.0
       B           200       3.0

In [ ]:
import pandas as pd
df = pd.read_csv('/content/diamonds.csv')
df.head()

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75

In [ ]:
df1 = df.drop(columns=['Unnamed: 0'])
df2 = df1.groupby(['color','clarity'])['price'].mean()
df3 = df2.reset_index()
df4 = df3.sort_values(by='price',ascending=False)
df4

   color clarity        price
1      D      IF  8307.369863
43     I     SI2  7002.649123
51     J     SI2  6520.958246
35     H     SI2  6099.895074
45     I     VS2  5690.505560
42     I     SI1  5355.019663
53     J     VS2  5311.058824
48     J      I1  5254.060000
50     J     SI1  5186.048000
55     J    VVS2  5142.396947
34     H     SI1  5032.414945
27     G     SI2  5021.684109
52     J     VS1  4884.461255
37     H     VS2  4722.414486
44     I     VS1  4633.183992
19     F     SI2  4472.625233
32     H      I1  4453.413580
29     G     VS2  4416.256498
40     I      I1  4302.184783
11     E     SI2  4173.826036
28     G     VS1  4131.362197
54     J    VVS1  4034.175676
3      D     SI2  3931.101460
0      D      I1  3863.023810
31     G    VVS2  3845.283437
20     F     VS1  3796.717742
36     H     VS1  3780.688623
26     G     SI1  3774.787449
21     F     VS2  3756.795093
18     F     SI1  3714.225716
9      E      IF  3668.506329
24     G      I1  3545.693333
8      E      I1  3488.421569
23     F    VVS2  3475.512821
49     J      IF  3363.882353
7      D    VVS2  3351.128391
16     F      I1  3342.181818
10     E     SI1  3161.838005
4      D     VS1  3030.158865
2      D     SI1  2976.146423
47     I    VVS2  2968.232877
6      D    VVS1  2947.912698
30     G    VVS1  2866.820821
12     E     VS1  2856.294301
22     F    VVS1  2804.276567
13     E     VS2  2750.941700
17     F      IF  2750.836364
39     H    VVS2  2649.067434
5      D     VS2  2587.225692
25     G      IF  2558.033774
15     E    VVS2  2499.674067
33     H      IF  2287.869565
14     E    VVS1  2219.820122
46     I    VVS1  2034.861972
41     I      IF  1994.937063
38     H    VVS1  1845.658120

In [ ]:
#Operations and np.where
df

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [ ]:
df['New'] = (df['x']+df['y']+df['z'])/3
df['new_price'] = df['price']+(df['price']*0.2)
df

KeyError: 'x'

In [ ]:
300 - 800
800 - 1500
1500 - 6000
6000 - 10000
More than 10000

In [ ]:
import numpy as np

df['new_price'] = np.where(df['color']=='E',df['price']*2,df['price'])
#df['new'] = np.where(df['color']=='D',1,
#            np.where(df['color']=='E',2,
#            np.where(df['color']=='F',3,0)))


df
D - 1
E - 2
F - 3
0
df

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z,New
0,1,0.23,Ideal,E,SI2,61.5,55.0,326.0,3.95,3.98,2.43,163.0
1,2,0.21,Premium,E,SI1,59.8,61.0,652.0,3.89,3.84,2.31,163.0
2,3,0.23,Good,E,VS1,56.9,65.0,327.0,4.05,4.07,2.31,163.5
3,4,0.29,Premium,I,VS2,62.4,58.0,668.0,4.20,4.23,2.63,167.0
4,5,0.31,Good,J,SI2,63.3,58.0,335.0,4.34,4.35,2.75,167.5
...,...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757.0,5.75,5.76,3.50,1378.5
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757.0,5.69,5.75,3.61,1378.5
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757.0,5.66,5.68,3.56,1378.5
53938,53939,0.86,Premium,H,SI2,61.0,58.0,5514.0,6.15,6.12,3.74,1378.5
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757.0,5.83,5.87,3.64,1378.5

In [ ]:
E = df['x']
J = df['y']
D = df['z']
other = x+y+z

In [ ]:
df['price'] = np.where(df['cut']=='Premium',df['price']*2,df['price'])
df

In [ ]:
import numpy as np
df1['x'] = np.where(df1['color']=='E',5,df1['x'])

In [ ]:
df1

,carat,cut,color,clarity,depth,table,price,x,y,z,xyz,x1,y1
0,0.23,Ideal,E,SI2,61.5,55.0,326,5.00,3.98,2.43,3.453333,X,3.95
1,0.21,Premium,E,SI1,59.8,61.0,326,5.00,3.84,2.31,3.346667,X,3.89
2,0.23,Good,E,VS1,56.9,65.0,327,5.00,4.07,2.31,3.476667,X,4.05
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,3.686667,4.2,4.23
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,3.813333,4.34,4.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,5.003333,5.75,5.76
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,5.016667,5.69,5.75
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,4.966667,5.66,5.68
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,5.336667,6.15,6.12
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,5.113333,5.83,5.87

In [ ]:
list1 = [1,2,3,4,5,6]

In [ ]:
list1[:] = 5

In [ ]:
list1

[1, 5, 3, 4, 5, 6]

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
a = pd.Series([1,2,3,4,5,6])
a = a.to_list()
print(a)
print(type(a))

[1, 2, 3, 4, 5, 6]
<class 'list'>

In [ ]:
plt.chartname(df1['x'],df1['y'])
sns.chartname(data=df1,x='x',y='y')